# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Marin le Maignan
email: marin.lemaignan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey, I'm Marin, 27, French
  I specialize in the research of ergonomy and simplicity in the web
  and like to wonder about the influence of the greatest tool ever created
  from a social as well as scientifical point of view.
  Also been playing guitar for now 20 years.
  Make artbooks. And actually got to have one of them bought by London's UAL
  historical collections department.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://marinlemaignan.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: marinlemaignan
github_username:  marinlemaignan

# Build settings
markdown: kramdown
theme: jekyll-swiss
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
